site_name: BioKT-PLUMED-docs 
site_url: https://github.com/BioKT/PLUMED-docs
nav:
    - Home: index.md
    - Setup: setup.md
    - Umbrella sampling: umbrella.md
    - Metadynamics: 
      - Alanine dipeptide in vacuum: metadynamics.md
      - Defining Q as collective variable: metadynamics-with-Q.md
    - Multiple replicas : replicas.md
    - PLUMED@DIPC: dipc.md
theme: readthedocs
markdown_extensions:
  - attr_list
  - md_in_html
